@php
    use NumberToWords\NumberToWords;
    // create the number to words "manager" class
$numberToWords = new NumberToWords();

// build a new number transformer using the RFC 3066 language identifier
$numberTransformer = $numberToWords->getNumberTransformer('en');
@endphp
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>invoice</title>
</head>

<body>

    <div class="" style="max-width:400px;margin:0 auto" id="">
        <div class="hidden-print">

                             <div class="d-flex justify-content-center mt-4">
                                <a href="{{ url('/sell/list') }}" class="btn btn-info btn-sm px-5">back</a>
                                <a href="javascipt:void(0);" onclick="printinvoice();" class="btn btn-primary btn-sm px-5 mx-2">Print</a>
                             </div>

        </div>
    </div>
        <hr>
        <div id="receipt-data">
            <div class="text-center mt-3" >
                <h3 class="">Yas Solution</h3>


                <p>Address: boropul, chittagong
                    <br>Phone Number: 1234
                </p>
            </div>
            @php
                $total=0;
                $change=0;
                $bid=0;
            @endphp
            @foreach ($bill as $bill)
            @php
                $total=$bill->total;
                $change=$bill->returned_ammount;
                $remaining=$bill->remaining;
                $bid=$bill->bill_id;
            @endphp
            <div style="max-width:400px;margin:0 auto" >
            <p>Date: {{ $bill->date }}<br>
                Reference: {{ $bill->reference_no }}<br>
                Customer: {{ Str::upper($bill->getCustomer->name) }}
            </p>
        </div>

            <table class="table-data" style="max-width:400px;margin:0 auto">
                <tbody>
                    @foreach ($bill_detail as $bill_detail)


                    <tr>
                        <td colspan="2" style="padding-right: 200px">
                            {{ $bill_detail->getproduct->product_name }}
                            <br>
                            {{ $bill_detail->qty ."x".$bill_detail->price." [Tax(".$bill_detail->tax."%)]" }}
                        </td>
                        <td style="text-align:right;vertical-align:bottom">{{ $bill_detail->total }}</td>
                    </tr>

                    @endforeach

                    <!-- <tfoot> -->

                    <tr>
                        <th colspan="2" style="text-align:left">Total</th>
                        <th style="text-align:right">{{ $bill->total }}</th>
                    </tr>
                    <tr>
                        <th colspan="2" style="text-align:left">Paid Amount</th>
                        <th style="text-align:right">{{ $bill->paid_ammount }}</th>
                    </tr>
                    <tr>
                        <td class="centered" colspan="10" style="">In Words:{{ $numberTransformer->toWords($bill->total); }}  only</td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                    </tr>
                    @endforeach
                </tbody>
                <!-- </tfoot> -->
            </table>
            <table style="max-width:400px;margin:0 auto">
                <tbody>
                    <tr style="background-color:#ddd;">
                        <td style="padding: 5px;width:30%;padding-left: 2px;">Amount: {{ $total }}</td>
                        <td style="padding: 5px;width:30%">Remaining: {{ $remaining }}</td>
                        {{-- <td style="width:30%"></td> --}}
                        <td style="padding: 5px;width:30%">Change: {{ $change }}</td>
                    </tr>

                    <tr>

                        <td class="centered" colspan="3" >Thank you for shopping with us. Please come again</td>
                    </tr>
                </tbody>
            </table>
            <div class="d-flex justify-content-center mb-2">{!! $barcode !!}</div>
            <!-- <div class="centered" style="margin:30px 0 50px">
<small>Invoice Generated By SalePro.
Developed By LionCoders</strong></small>
</div> -->
        </div>

    <script>
        function printinvoice(){
    var body=document.body.innerHTML;
    var printDiv=document.getElementById('receipt-data').innerHTML;
    document.body.innerHTML=printDiv;
    window.print();
    document.body.innerHTML=body;

        }
    </script>
</body>

</html>
